import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Download,
  FileText,
  Search,
  Share2,
  BarChart,
  PieChart,
  LineChart,
} from "lucide-react";

export default function ReportsPage() {
  return (
    <div className="flex-1 space-y-4 p-8 pt-6">
      <div className="flex items-center justify-between space-y-2">
        <h2 className="text-3xl font-bold tracking-tight">Forest Reports</h2>
        <div className="flex items-center space-x-2">
          <Button variant="outline">
            <Download className="mr-2 h-4 w-4" />
            Export
          </Button>
          <Button variant="outline">
            <Share2 className="mr-2 h-4 w-4" />
            Share
          </Button>
          <Button>
            <FileText className="mr-2 h-4 w-4" />
            Generate Report
          </Button>
        </div>
      </div>
      <Tabs defaultValue="inventory" className="space-y-4">
        <TabsList>
          <TabsTrigger value="inventory">Inventory</TabsTrigger>
          <TabsTrigger value="wildlife">Wildlife</TabsTrigger>
          <TabsTrigger value="activities">Activities</TabsTrigger>
          <TabsTrigger value="health">Forest Health</TabsTrigger>
        </TabsList>
        <TabsContent value="inventory" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Inventory Reports</CardTitle>
              <CardDescription>
                Comprehensive reports on forest inventory data.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex items-center justify-between mb-4">
                <div className="space-x-2 flex items-center">
                  <div className="relative w-64">
                    <Search className="absolute left-2 top-2.5 h-4 w-4 text-muted-foreground" />
                    <Input placeholder="Search reports..." className="pl-8" />
                  </div>
                  <Select defaultValue="2023">
                    <SelectTrigger className="w-[180px]">
                      <SelectValue placeholder="Select Year" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="2023">2023</SelectItem>
                      <SelectItem value="2022">2022</SelectItem>
                      <SelectItem value="2021">2021</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="flex items-center space-x-2">
                  <Button variant="outline" size="sm" className="h-8 gap-1">
                    <BarChart className="h-4 w-4" />
                    Bar
                  </Button>
                  <Button variant="outline" size="sm" className="h-8 gap-1">
                    <PieChart className="h-4 w-4" />
                    Pie
                  </Button>
                  <Button variant="outline" size="sm" className="h-8 gap-1">
                    <LineChart className="h-4 w-4" />
                    Line
                  </Button>
                </div>
              </div>

              <div className="space-y-6">
                <div>
                  <h3 className="text-lg font-medium mb-2">
                    Tree Species Distribution
                  </h3>
                  <div className="h-80 border rounded-md p-4 flex items-center justify-center bg-gray-50">
                    <p className="text-muted-foreground">
                      [Interactive Tree Species Distribution Chart]
                    </p>
                  </div>
                </div>

                <div>
                  <h3 className="text-lg font-medium mb-2">
                    Recent Inventory Reports
                  </h3>
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Report Name</TableHead>
                        <TableHead>Date Generated</TableHead>
                        <TableHead>Forest Area</TableHead>
                        <TableHead>Inventory Type</TableHead>
                        <TableHead>Generated By</TableHead>
                        <TableHead className="text-right">Actions</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      <TableRow>
                        <TableCell className="font-medium">
                          Annual Inventory Summary 2023
                        </TableCell>
                        <TableCell>June 15, 2023</TableCell>
                        <TableCell>All Sectors</TableCell>
                        <TableCell>Comprehensive</TableCell>
                        <TableCell>System</TableCell>
                        <TableCell className="text-right">
                          <Button variant="ghost" size="sm">
                            <Download className="h-4 w-4" />
                          </Button>
                        </TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell className="font-medium">
                          Northern Sector Tree Survey
                        </TableCell>
                        <TableCell>May 20, 2023</TableCell>
                        <TableCell>North Sector</TableCell>
                        <TableCell>Trees Only</TableCell>
                        <TableCell>J. Smith</TableCell>
                        <TableCell className="text-right">
                          <Button variant="ghost" size="sm">
                            <Download className="h-4 w-4" />
                          </Button>
                        </TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell className="font-medium">
                          Equipment Status Report
                        </TableCell>
                        <TableCell>May 10, 2023</TableCell>
                        <TableCell>N/A</TableCell>
                        <TableCell>Equipment</TableCell>
                        <TableCell>M. Johnson</TableCell>
                        <TableCell className="text-right">
                          <Button variant="ghost" size="sm">
                            <Download className="h-4 w-4" />
                          </Button>
                        </TableCell>
                      </TableRow>
                    </TableBody>
                  </Table>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
        <TabsContent value="wildlife" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Wildlife Reports</CardTitle>
              <CardDescription>
                Comprehensive reports on wildlife population and health.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex items-center justify-between mb-4">
                <div className="space-x-2 flex items-center">
                  <div className="relative w-64">
                    <Search className="absolute left-2 top-2.5 h-4 w-4 text-muted-foreground" />
                    <Input placeholder="Search reports..." className="pl-8" />
                  </div>
                  <Select defaultValue="mammals">
                    <SelectTrigger className="w-[180px]">
                      <SelectValue placeholder="Select Category" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="mammals">Mammals</SelectItem>
                      <SelectItem value="birds">Birds</SelectItem>
                      <SelectItem value="insects">Insects</SelectItem>
                      <SelectItem value="aquatic">Aquatic</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="flex items-center space-x-2">
                  <Button variant="outline" size="sm" className="h-8 gap-1">
                    <BarChart className="h-4 w-4" />
                    Bar
                  </Button>
                  <Button variant="outline" size="sm" className="h-8 gap-1">
                    <LineChart className="h-4 w-4" />
                    Line
                  </Button>
                </div>
              </div>

              <div className="space-y-6">
                <div>
                  <h3 className="text-lg font-medium mb-2">
                    Wildlife Population Trends (5-Year)
                  </h3>
                  <div className="h-80 border rounded-md p-4 flex items-center justify-center bg-gray-50">
                    <p className="text-muted-foreground">
                      [Interactive Wildlife Population Trend Chart]
                    </p>
                  </div>
                </div>

                <div>
                  <h3 className="text-lg font-medium mb-2">
                    Wildlife Monitoring Reports
                  </h3>
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Report Name</TableHead>
                        <TableHead>Date Generated</TableHead>
                        <TableHead>Species Group</TableHead>
                        <TableHead>Status Summary</TableHead>
                        <TableHead>Generated By</TableHead>
                        <TableHead className="text-right">Actions</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      <TableRow>
                        <TableCell className="font-medium">
                          Deer Population Assessment
                        </TableCell>
                        <TableCell>June 1, 2023</TableCell>
                        <TableCell>Mammals</TableCell>
                        <TableCell>Stable/Increasing</TableCell>
                        <TableCell>Wildlife Team</TableCell>
                        <TableCell className="text-right">
                          <Button variant="ghost" size="sm">
                            <Download className="h-4 w-4" />
                          </Button>
                        </TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell className="font-medium">
                          Spring Bird Migration Report
                        </TableCell>
                        <TableCell>May 15, 2023</TableCell>
                        <TableCell>Birds</TableCell>
                        <TableCell>Normal Patterns</TableCell>
                        <TableCell>J. Smith</TableCell>
                        <TableCell className="text-right">
                          <Button variant="ghost" size="sm">
                            <Download className="h-4 w-4" />
                          </Button>
                        </TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell className="font-medium">
                          Aquatic Species Survey
                        </TableCell>
                        <TableCell>April 30, 2023</TableCell>
                        <TableCell>Aquatic</TableCell>
                        <TableCell>Mixed Results</TableCell>
                        <TableCell>Watershed Team</TableCell>
                        <TableCell className="text-right">
                          <Button variant="ghost" size="sm">
                            <Download className="h-4 w-4" />
                          </Button>
                        </TableCell>
                      </TableRow>
                    </TableBody>
                  </Table>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
        <TabsContent value="activities" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Activities Reports</CardTitle>
              <CardDescription>
                Comprehensive reports on forest management activities.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex items-center justify-between mb-4">
                <div className="space-x-2 flex items-center">
                  <div className="relative w-64">
                    <Search className="absolute left-2 top-2.5 h-4 w-4 text-muted-foreground" />
                    <Input placeholder="Search reports..." className="pl-8" />
                  </div>
                  <Select defaultValue="maintenance">
                    <SelectTrigger className="w-[180px]">
                      <SelectValue placeholder="Select Activity Type" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="maintenance">Maintenance</SelectItem>
                      <SelectItem value="planting">Planting</SelectItem>
                      <SelectItem value="harvesting">Harvesting</SelectItem>
                      <SelectItem value="conservation">Conservation</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <div className="space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <Card>
                    <CardHeader className="pb-2">
                      <CardTitle className="text-sm font-medium">
                        Activity Completion Rate
                      </CardTitle>
                    </CardHeader>
                    <CardContent>
                      <div className="h-60 flex items-center justify-center bg-gray-50 rounded-md">
                        <p className="text-muted-foreground">
                          [Activity Completion Chart]
                        </p>
                      </div>
                    </CardContent>
                  </Card>
                  <Card>
                    <CardHeader className="pb-2">
                      <CardTitle className="text-sm font-medium">
                        Activities by Type
                      </CardTitle>
                    </CardHeader>
                    <CardContent>
                      <div className="h-60 flex items-center justify-center bg-gray-50 rounded-md">
                        <p className="text-muted-foreground">
                          [Activities by Type Chart]
                        </p>
                      </div>
                    </CardContent>
                  </Card>
                </div>

                <div>
                  <h3 className="text-lg font-medium mb-2">
                    Recent Activity Reports
                  </h3>
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Report Name</TableHead>
                        <TableHead>Date Generated</TableHead>
                        <TableHead>Activity Type</TableHead>
                        <TableHead>Status</TableHead>
                        <TableHead>Generated By</TableHead>
                        <TableHead className="text-right">Actions</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      <TableRow>
                        <TableCell className="font-medium">
                          Q2 Planting Progress Report
                        </TableCell>
                        <TableCell>June 30, 2023</TableCell>
                        <TableCell>Planting</TableCell>
                        <TableCell>On Schedule</TableCell>
                        <TableCell>System</TableCell>
                        <TableCell className="text-right">
                          <Button variant="ghost" size="sm">
                            <Download className="h-4 w-4" />
                          </Button>
                        </TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell className="font-medium">
                          Trail Maintenance Summary
                        </TableCell>
                        <TableCell>May 31, 2023</TableCell>
                        <TableCell>Maintenance</TableCell>
                        <TableCell>Completed</TableCell>
                        <TableCell>T. Williams</TableCell>
                        <TableCell className="text-right">
                          <Button variant="ghost" size="sm">
                            <Download className="h-4 w-4" />
                          </Button>
                        </TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell className="font-medium">
                          Selective Harvesting Analysis
                        </TableCell>
                        <TableCell>May 15, 2023</TableCell>
                        <TableCell>Harvesting</TableCell>
                        <TableCell>In Progress</TableCell>
                        <TableCell>M. Johnson</TableCell>
                        <TableCell className="text-right">
                          <Button variant="ghost" size="sm">
                            <Download className="h-4 w-4" />
                          </Button>
                        </TableCell>
                      </TableRow>
                    </TableBody>
                  </Table>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
        <TabsContent value="health" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Forest Health Reports</CardTitle>
              <CardDescription>
                Comprehensive reports on overall forest ecosystem health.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex items-center justify-between mb-4">
                <div className="space-x-2 flex items-center">
                  <div className="relative w-64">
                    <Search className="absolute left-2 top-2.5 h-4 w-4 text-muted-foreground" />
                    <Input placeholder="Search reports..." className="pl-8" />
                  </div>
                  <Select defaultValue="all">
                    <SelectTrigger className="w-[180px]">
                      <SelectValue placeholder="Select Forest Area" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">All Areas</SelectItem>
                      <SelectItem value="north">North Sector</SelectItem>
                      <SelectItem value="south">South Sector</SelectItem>
                      <SelectItem value="east">East Sector</SelectItem>
                      <SelectItem value="west">West Sector</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <div className="space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <Card>
                    <CardHeader className="pb-2">
                      <CardTitle className="text-sm font-medium">
                        Biodiversity Index
                      </CardTitle>
                    </CardHeader>
                    <CardContent className="pt-0">
                      <div className="text-2xl font-bold">87/100</div>
                      <p className="text-xs text-muted-foreground">
                        ↑ 3 points from last year
                      </p>
                      <div className="h-40 flex items-center justify-center mt-2">
                        <p className="text-muted-foreground">
                          [Biodiversity Trend]
                        </p>
                      </div>
                    </CardContent>
                  </Card>
                  <Card>
                    <CardHeader className="pb-2">
                      <CardTitle className="text-sm font-medium">
                        Carbon Sequestration
                      </CardTitle>
                    </CardHeader>
                    <CardContent className="pt-0">
                      <div className="text-2xl font-bold">1,250 tons</div>
                      <p className="text-xs text-muted-foreground">
                        ↑ 5% from last year
                      </p>
                      <div className="h-40 flex items-center justify-center mt-2">
                        <p className="text-muted-foreground">
                          [Carbon Sequestration Trend]
                        </p>
                      </div>
                    </CardContent>
                  </Card>
                  <Card>
                    <CardHeader className="pb-2">
                      <CardTitle className="text-sm font-medium">
                        Forest Resilience Score
                      </CardTitle>
                    </CardHeader>
                    <CardContent className="pt-0">
                      <div className="text-2xl font-bold">72/100</div>
                      <p className="text-xs text-muted-foreground">
                        ↑ 2 points from last year
                      </p>
                      <div className="h-40 flex items-center justify-center mt-2">
                        <p className="text-muted-foreground">
                          [Resilience Score Trend]
                        </p>
                      </div>
                    </CardContent>
                  </Card>
                </div>

                <div>
                  <h3 className="text-lg font-medium mb-2">
                    Health Assessment Reports
                  </h3>
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Report Name</TableHead>
                        <TableHead>Date Generated</TableHead>
                        <TableHead>Forest Area</TableHead>
                        <TableHead>Health Status</TableHead>
                        <TableHead>Generated By</TableHead>
                        <TableHead className="text-right">Actions</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      <TableRow>
                        <TableCell className="font-medium">
                          Annual Health Assessment
                        </TableCell>
                        <TableCell>June 1, 2023</TableCell>
                        <TableCell>All Areas</TableCell>
                        <TableCell>Good</TableCell>
                        <TableCell>Ecology Team</TableCell>
                        <TableCell className="text-right">
                          <Button variant="ghost" size="sm">
                            <Download className="h-4 w-4" />
                          </Button>
                        </TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell className="font-medium">
                          Pest & Disease Monitoring
                        </TableCell>
                        <TableCell>May 15, 2023</TableCell>
                        <TableCell>All Areas</TableCell>
                        <TableCell>Minor Issues</TableCell>
                        <TableCell>Plant Health Team</TableCell>
                        <TableCell className="text-right">
                          <Button variant="ghost" size="sm">
                            <Download className="h-4 w-4" />
                          </Button>
                        </TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell className="font-medium">
                          Soil Quality Analysis
                        </TableCell>
                        <TableCell>May 1, 2023</TableCell>
                        <TableCell>All Areas</TableCell>
                        <TableCell>Good</TableCell>
                        <TableCell>Soil Science Team</TableCell>
                        <TableCell className="text-right">
                          <Button variant="ghost" size="sm">
                            <Download className="h-4 w-4" />
                          </Button>
                        </TableCell>
                      </TableRow>
                    </TableBody>
                  </Table>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}
